### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#1]
What needs to happen to get the site to a state that more of us can help contribute?

@jenlampton, Do you have a site started locally with some existing config or could I start a new site locally and share the database/config files to help us get started?

Once we start working on BackdropCMS.org infrastructure, who will have permission to push code changes to the live site?

**Comment by jenlampton** [comment]
I need to push the db up and commit config, then anyone in the devops group can deploy.

**Comment by jenlampton** [comment]
Pushed current config to github.

**Comment by stpaultim** [comment]
Ok, I'm happy to help with the site and will try working on the site locally and pushing features using config. However, I need the following:

1) Access to a copy of the database? (I think I need that)
2) An account to access the site. Registration is closed.
3) Information about how to get code pushed. I can create a PR against this repo, but will someone know to deploy it OR do I need to contact someone (who all is on the devops group)?

**Comment by jenlampton** [comment]
I thought I put the drop pw in 1Password, but we should open up account
creation anyway. I'll can do that after dinner :)

For deploys, myself, bwpanda, and justin are the usual suspects. Do you
want access too so you can pull your own changes?

**Comment by stpaultim** [comment]
You may have put password into 1Password, it didn't occur to me to check. I'll do so.

I think it might make sense for me to be able to deploy code to this site. If that works, otherwise just knowing who to bug also helps. :-)

**Comment by jenlampton** [comment]
account creation has been enabled: https://events.backdropcms.org/user/register?a=b

**Comment by stpaultim** [comment]
@jenlampton - If you put the password into 1Password, then you must not have shared it with others (or at least not with me, I can't find it there). 

I will create an account now, but I don't expect I will have permissions to do anything.

**Comment by stpaultim** [comment]
@jenlampton - nevermind. Apparently I already have an account with admin access. Either I created it and  forgot or you set me up. 

:-)
