### ISSUE TITLE
Add User Time Zone Tokens + Token Filter and test.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/events.backdropcms.org#19]
Figuring out when a discussion is happening in your own timezone is not straightforward enough.

We have no way of (reliably) determining your timezone without specifically asking you (many browser regions don't match with Backdrop's master list of timezones). In order to track your timezone, we either need to store it as part of your user record (which would only work if you are logged in) or in a session cookie (which would only work in one browser).

**People have struggled most with having the timezones change**. If you look at the schedule from your phone (logged out), and see one time, and then look at the schedule from your computer (logged in) and see another time, it's really difficult to show up at the correct time for that session.

I think there might be a way we can solve this problem:

Always display a single static time (Perhaps in UTC), and then ALSO display a second time that we clearly label as a GUESS as a match for your local timezone. Everyone would then only need to see 2 timezones (instead of the 8 we are showing currently) and they'd be warned that the variable one might not be correct.

For those who are logged in, we can add a link to allow them to correct a timezone that was guessed incorrectly, but for those who are logged out we'll need to add some other kind of obvious label or highlight indicating the timezone might not be accurate.

@bugfolder recommended a combination of [User Time Zone Tokens](https://github.com/backdrop-contrib/utz_tokens) + [Luxon](https://github.com/backdrop-contrib/luxon) for the variable session time, though I'm not sure yet how that will work with a date field, I think we should try it and see if it's an improvement. 

> User Time Zone Tokens provides a field formatter for the three Date type fields.

Ah, that's how! :D

**Comment by bugfolder** [comment]
[User Time Zone Tokens](https://github.com/backdrop-contrib/utz_tokens) provides both token text and a date field formatter that both work pretty much the same way.

@indigoxela also has a nice date field formatter module, [Client Side Date Field Formatter](https://github.com/backdrop-contrib/cs_date_formatter).

UTZ Tokens's configuration gives three options for how to handle authenticated versus anonymous users:

![UTZ tokens config](https://user-images.githubusercontent.com/29214084/125177308-95849880-e18f-11eb-8a40-682a314e6107.jpg)

It's possible when specifying how the date is rendered to include the timezone abbreviation (the 'T' specifier in PHP's DateTiime formatter), so if one is using the browser timezone option and the browser guesses wrongly, it will at least be visible to the user as an unrecognizeable abbreviation.

And if we chose the second option, "user's timezone for authenticated users, browser's timezone for anonymous users", then we could add some text for anonymous users that says "if you're not seeing the correct timezone, please login and set the timezone for your user account." Or something like that.

We've been using the D7 back-port of UTZ Tokens for a couple of months on the site I run for some international online conferences, and it's worked pretty well.

**Comment by jenlampton** [comment]
@bugfolder Do you know what timezone is used when there is no match? Does it fallback to the timezone that was provided with the date?

**Comment by bugfolder** [comment]
Possibly I'm not understanding "no match". Maybe this: if the user has set their timezone, then it uses that timezone. If the user hasn't set their timezone explicitly, then it's whatever the site default is for tha situation, ditto for anonymous users.

**Comment by jenlampton** [comment]
> If the user hasn't set their timezone explicitly, then it's whatever the site default is for tha situation, ditto for anonymous users.

Yeah, I was asking what the site default was or where that was set. I'll enable the modules though and give it a try. I'm sure it will become clear once I see in in action :)

**Comment by stpaultim** [comment]
Going to close this ticket. We used this module during last Backdrop LIVE and it seems to have worked well. Using it again for the next Backdrop LIVE.

**Comment by jenlampton** [comment]
> and it seems to have worked well. 

Is there another ticket addressing all the timezones where it failed? Greece, Buenos Aires, and all the others?

**Comment by stpaultim** [comment]
I never heard any complaints from anyone about any time zones. 

Are you thinking about your other event?

To my knowledge, no one reported any problems in regards to our event.

**Comment by stpaultim** [comment]
@jenlampton - I never heard any complaints from anyone about Backdrop LIVE, unless it happened at a meeting that I did not attend. 

There were some complaints recently, when our initial attempt to use this module didn't work correctly on BackdropCMS.org. To my knowledge that problem was addressed and that it later worked for those people. 

So, I am unaware of any current complaints that this modules is not working for anyone. However, let's check with folks to be sure.

**Comment by jenlampton** [comment]
I could be thinking of b.org, @bugfolder would know more as I think he was working on a fix.

**Comment by bugfolder** [comment]
I was at the meeting, and we determined that at least part (or perhaps all?) of the failures were due to having the setting on the second button, using the user account's time zone if set. That was failing because Backdrop was caching the page using data from the last user account that accessed that page post-cached-clear. So we set it to the third setting, always use the client-side setting, and that seemed to fix many of the problems.

So at the very least we should re-test, now that it's on the proper setting compatible with current caching.

**Comment by stpaultim** [comment]
I've put a fresh message in Zulip asking folks to test for us. I'm very happy to be thorough about testing and making sure that this isn't a problem. I just wasn't aware of any problems that we were not able to resolve.

**Comment by stpaultim** [comment]
I've asked a number of people to check this and have not gotten any reports of ongoing issues with this feature. Let's leave this issue open through Backdrop LIVE 5 and see if we get any reports.

**Comment by irinaz** [comment]
Worked great for several Backdrop Live events, closing ticket
