### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#2]
How do we want to handle registration?

If you are not able to get this part done quickly, feel free to outline quickly how you think it should be set up and I can get something working either locally or on Simplo and then we can move it when it's ready.

@jenlampton

**Comment by jenlampton** [comment]
I am using the entity registration module + event nodes.

**Comment by jenlampton** [comment]
Registration form ready for testing, here: https://events.backdropcms.org/events/backdrop-live-march-2021

**Comment by stpaultim** [comment]
Do we want to have a donation form ready before we officially open for registration? It's hard to go back and ask for donations once someone has already registered. 

We could have a pre-registration form that is about saying, please contact me when registration is open. 

Also - I think that we want folks to create accounts, don't we. So, it's been my impression that users would create an account before registering.

**Comment by jenlampton** [comment]
I have an add-on module that creates accounts for people automatically as they register: https://github.com/backdrop-contrib/registration/issues/21

**Comment by jenlampton** [comment]
> Do we want to have a donation form ready before we officially open for registration? It's hard to go back and ask for donations once someone has already registered.

Ah, right! I think we need to contact SFC about this...  I'll send them an email.

**Comment by jenlampton** [comment]
I re-read our previous correspondence with the SFC on accepting Paypal payments, and they had asked for more than a month lead time in order to set up payment processing. Last time, we got away with a shorter planning window because they already had a process for using Eventbrite. I'm concerned about how quickly they will get back to us on this.

**Comment by jenlampton** [comment]
Registration is up, but I've created https://github.com/backdrop-ops/events.backdropcms.org/issues/3 where we can work on donations. I'm going to close this (but we can create new issues if/when issues are discovered with the registration process)
