### ISSUE TITLE
Schedule for March 2022 event points to schedule for Oct 2021 

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/events.backdropcms.org#23]
I imagine people may soon start to want to suggest ideas for the next event.  The listing on https://events.backdropcms.org has a link that points to the schedule for October 2021 which may be misleading.

Is the discussion topic content type associated with an event or could it be?

![image](https://user-images.githubusercontent.com/20357797/150760405-4a223a7a-723d-450f-be42-6f02d884b6c9.png)

![image](https://user-images.githubusercontent.com/20357797/150760618-91048994-d467-4409-9062-b53093b900a2.png)

**Comment by stpaultim** [comment]
This is fixed.
