### ISSUE TITLE
'Next Steps' or 'What to Do' block

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#27]
I had removed this block (I thought) and replaced it with a "Things to Do" block as a temporary measure, based upon the following feedback. 

The old format makes it look like you MUST make a donation before you can suggest a topic or post a video presentation.

Also, the Step 1, Step 2, Step 3 format suggested a necessary order, which might not always be applicable. I was hoping that we might make some changes to the original block before restoring it. 

Now, I see that in some places, the old block seems to be back while in others, my block is still there.

It is possible, that I just didn't make the change everywhere I thought I did. But, before I start making more changes, I'd like to be sure we're on the same page here.

**Comment by stpaultim** [comment]
This is getting much discussion in Zulip at the moment. 

It seems that in fact the "donation" step is considered a "required" step in the process. It is required in the sense that we expect everyone to at least consider a donation. If they don't feel that they are able to, they can opt out. But, we do expect folks to at least consider a donation, the amount of which is up to them. 

Here is the current language on the site.

![image](https://user-images.githubusercontent.com/3144571/153670395-3b8d268c-cb3d-4f5a-8570-2ff3fd2ca262.png)

I found my temporary replacement block was still visible on at least one layout and I restored the original block.

**Comment by jenlampton** [comment]
There are a lot more problems with the new custom block as compared to the old one. For staters, all of the links in the new custom are hard-coded, so most of the links will be broken, most of the time, for most people. (The old block dynamically changed the links based on the status of the person viewing the block)

I have restored the previous version of the block with not-broken links on all pages, and deleted the problematic one. 

In general, it would be good to document any problems with something, so that those problems can be addressed without introducing new ones :)

## These are the *known* issues with the dynamic block (that are hard to fix)

1) Backdrop can't tell if you've made a donation or not, so there is no checkmark added to #3

## These are the *perceived* issues with the dynamic block, that should have more discussion before changes can be 
made

> 1) The old format makes it look like you MUST make a donation before you can suggest a topic or post a video presentation.

This is correct (because the donation is part of registration)

> Also, the Step 1, Step 2, Step 3 format suggested a necessary order

It's important that someone knows they must create an account before they can register for the event. It's important to communicate the necessary order for 1 and 2. And since 3 is really a part of 2, that should also come as 3. 

Because someone needs to be a registered attendee for the current event before they can submit a presentation and/or discussion for that event, number 4 and 5 need to come after number 3, but you are correct that they could go in any order. 

Maybe we could add these items in a separate list below 1, 2, and 3, with a new heading that reads "Once you are registered..." or something similar? I can start working on that now :) -- please provide suggestions for the heading if you don't like "Once you are registered..."

**Comment by stpaultim** [comment]
I'm good. I was just trying to implement a short term solution to problems that were being brought to me by other people, until we could fix the original block. Clearly, it was not my intention to make things worse. 

I'm comfortable going back to the original block. I think the concerns that were raised are being addressed as I hoped they would be. It was always my intention to get feedback, fix the original block, and restore it. 

That seems to be the outcome, so I'm happy. Sorry for any temporary inconvenience.

**Comment by jenlampton** [comment]
No ned to apologize, I just need to know what I should be fixing :)

**Comment by irinaz** [comment]
I logged in, registered, made a donation and suggested a discussion.  I see checkmark next to first two steps, no checkmark next to steps 3 and 4.   Not sure if this is a bug or checkmarks are not available in this block.  Thanks!

**Comment by klonos** [comment]
Confirming what @irinaz said ^^

**Comment by jenlampton** [comment]
No, the donation is not optional.

**Comment by klonos** [comment]
Oh, sorry then. I had it wrong all along. ...but in all truth, I think that it should be a free event - but I'm sure there are reasons. I'll have a think about it ...perhaps I shouldn't be that concerned.

**Comment by irinaz** [comment]
> There are a lot more problems with the new custom block as compared to the old one. For staters, all of the links in the new custom are hard-coded, so most of the links will be broken, most of the time, for most people. (The old block dynamically changed the links based on the status of the person viewing the block)
> 
> I have restored the previous version of the block with not-broken links on all pages, and deleted the problematic one.
> 
> In general, it would be good to document any problems with something, so that those problems can be addressed without introducing new ones :)
> 
> ## These are the _known_ issues with the dynamic block
> 1. Backdrop can't tell if you've made a donation or not, so there is no checkmark added to 3  (this is hard to fix)
> 2. There is no checkmark added for 4 or 5 (these are easier to fix)
> 
> ## These are the _perceived_ issues with the dynamic block, that should have more discussion before changes can be
> made
> 
> > 1. The old format makes it look like you MUST make a donation before you can suggest a topic or post a video presentation.
> 
> This is correct (because the donation is part of registration)
> 
> > 2. Also, the Step 1, Step 2, Step 3 format suggested a necessary order
> 
> It's important that someone knows they must create an account before they can register for the event. It's important to communicate the necessary order for 1 and 2. And since 3 is really a part of 2, that should also come as 3.
> 
> Because someone needs to be a registered attendee for the current event before they can submit a presentation and/or discussion for that event, number 4 and 5 need to come after number 3, but you are correct that they could go in any order.
> 
> Maybe we could add these items in a separate list below 1, 2, and 3, with a new heading that reads "Once you are registered..." or something similar? I can start working on that now :) -- please provide suggestions for the heading if you don't like "Once you are registered..."

One suggestion would be to separate step 1 and 2 from other links as they have different behaviour.  Or maybe we can hide them for those who already have account and registration instead of adding checkmark.  If we remove text "step 1"  and keep bullets it would be easy to do.

**Comment by irinaz** [comment]
> > can we please at least append ` (optional)` as a suffix to the link
> 
> No, the donation is not optional. This is not a free event.

From technical perspective I do not have checkbox next to Make donation after I made a donation.

**Comment by jenlampton** [comment]
> From technical perspective I do not have checkbox next to Make donation after I made a donation.   

@irinaz please read [the comment](https://github.com/backdrop-ops/events.backdropcms.org/issues/27#issuecomment-1036700468) above where this was mentioned.

**Comment by jenlampton** [comment]
As a first step, I've removed the links from item 1 and 2 (once they are done) so that it is clear that it is not necessary to do them again. Let's see if this helps: https://events.backdropcms.org/faq

**Comment by jenlampton** [comment]
> There is no checkmark added for 4 or 5 (these are easier to fix)

As a second step, I have added checkmarks next to 4 and 5 if people have done those things.

**Comment by irinaz** [comment]
Thanks for all updates!!!

**Comment by jenlampton** [comment]
As a next step, I separated the list of steps into 1,2,3 and 4,5,6 and separated them with headings `Register now` and `Next steps` (suggestions welcome)...  

I added a "view the schedule" link as #4, and moved 5,6 down below that one. (and removed the numbers from 4,5 and 6)
https://events.backdropcms.org/archive

Here's where we are now:
<img width="411" alt="Screen Shot 2022-02-11 at 6 46 18 PM" src="https://user-images.githubusercontent.com/397895/153693735-68121d0c-ba05-42ab-8d81-ef269885dfed.png">

What should I do next?

**Comment by stpaultim** [comment]
I just registered as "Rajib" and I'm not seeing a check mark in the right place.

![image](https://user-images.githubusercontent.com/3144571/153694474-0f670486-6fb1-478f-a01f-9e3e8719cd08.png)

**Comment by stpaultim** [comment]
@jenlampton - For reference. If I click on the Register link, I get a blank page that says "Welcome to Backdrop LIVE" with no chance to register again. So the registration is recognized, it's just not registering in the "register now" block.

**Comment by jenlampton** [comment]
Thanks, I'll have a look!

**Comment by stpaultim** [comment]
A user just reported being confused about the "Next Steps" block, because they are already registered but the lack of a checkmark let them to believe they must register again. They reported thinking that they must register for each session.

**Comment by jenlampton** [comment]
looking now.

**Comment by irinaz** [comment]
I am not quite sure why I would want to see steps that I already completed.  If I am logged in that means that I already created an account. @jenlampton, would it make sense to hide items that are completed (create account) and keep list of things to do(make a donation)?

**Comment by jenlampton** [comment]
no, removing things frustrated people. they think "I could have sworn I saw it somewhere". I think all we need to do is make the checkmark work :)

**Comment by jenlampton** [comment]
I finally got the bug fixed :) I'm going to close this issue but if other things come up that need to be addressed with this block, please open new ones!
