### ISSUE TITLE
Add ability for users to flag events

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#29]
It was suggested in Zulip that we add a "I plan on attending" flag to topics on the schedule. The idea that to show a list of people who plan on attending specific topics or at least to gauge interest.

My own thought is that with a continually evolving schedule, I don't expect people to decide on specific topics in advance. However, having an "I'm interested in this Topic" flag could be interesting. 

See what topics get the most response, might inspire folks to suggest other similar or related topics. 

Also, if we see that the two most popular topics are scheduled at the same time, we could try to make an adjustment in the schedule so that more people can attend them.

**Comment by irinaz** [comment]
Look like this has been configured as well as block with list of users who are interested in a discussion.  Do we want to @stpaultim , do we want to extend this functionality to allow users to see their own schedule or we should close this issue?

**Comment by irinaz** [comment]
Flagging has been set, closing issue, moving to work on  #9
