### ISSUE TITLE
Suggested Donations

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/events.backdropcms.org#3]
I'm creating this issue to cover suggested donations along with event registration. 

> Do we want to have a donation form ready before we officially open for registration? It's hard to go back and ask for donations once someone has already registered.

Ah, right! I think we need to contact SFC about this... I'll send them an email.

...

I re-read our previous correspondence with the SFC on accepting Paypal payments, and they had asked for more than a month lead time in order to set up payment processing. Last time, we got away with a shorter planning window because they already had a process for using Eventbrite. I'm concerned about how quickly they will get back to us on this.

**Comment by jenlampton** [comment]
I have an idea!

I have been working on a `paypal_smart` contrib module for another site that recreates the features from PayPal "Smart buttons" including the field for variable donation amount. 

I would like to set up this module on the b-live site so that we can open registration. Once we get approval from SFC, it should be easy to switch over the destination paypal account. We can also send them the paypal balance at that time, or even each payment as we receive it. Fingers crossed that we hear from them soon enough that those transactions are only our tests!

**Comment by stpaultim** [comment]
@jenlampton - We need to come up with our backup plan if we are not able to get this working quickly. We might need to ask if Eventbrite will speed things along any.

**Comment by oadaeh** [comment]
This seems to be done now.
