### ISSUE TITLE
Consider elimination of block D? 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#30]
The original idea for Backdrop LIVE was to have a schedule that went with 3 hour blocks of topics interspersed with 3 hour breaks on a 24 hour schedule. We hoped that this might help us cater to a global audience and provide programming in all time zones. 

However, we are finding it very hard to get anyone interested in Block D. This is 2:00AM - 5:00AM (Pacific Time) or 11:00AM-2:00PM (Central European Time). 

Unless we see some interest in programming during this time slot, I would suggest that we eliminate it and simply have a 9 hour break during this time frame. 

We have gotten some participation during this time slot in the past, I would estimate between 4 and 8 people at most. We have had up to 3 sessions during this block.

Starting with the last Backdrop LIVE, we now have someone in Europe that is available to serve as hall monitor during this time frame and make sure that the rooms are open and is available to answer any questions. Thanks @DrAlbany 

But it is worth the effort to keep this time slot available.

**Comment by oadaeh** [comment]
I think this has been decided and can be closed?
