### ISSUE TITLE
Make Sanitized database available

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#4]
The main blocker for any real cooperative development on the Events site is availability of an initial database. 

Can we hook the events site into the same sanitize process that Backdropcms.org, forum, and docs are on? That way contributors can always get caught up. 

 - - - - - -

FYI - Good work on the security. I tried to be clever and enable the project module to install backup and migrate, but the permissions are not set up to allow that (which I am sure is quite deliberate). The current database has no data in it that needs to be sanitized, so I just need a copy any way possible. 

@backdrop-ops/backdrop-web-team

Or @jenlampton or @BWpanda or @larsdesigns

**Comment by BWPanda** [comment]
I have configured the Sanitize site to dump and display DBs and Files for the Events site, however I need @larsdesigns help with fixing the DB user permissions. Once that's done, it should be working.

**Comment by stpaultim** [comment]
Checking back on this issue. @BWPanda or @larsdesigns ?

**Comment by larsdesigns** [comment]
I will have a look this morning.

**Comment by larsdesigns** [comment]
I added the permissions for the events temp database and tested using the cron job. It seems to be working now.

**Comment by BWPanda** [comment]
Thanks @larsdesigns! @stpaultim this should be working now.

**Comment by stpaultim** [comment]
Yeah. I've tested and this seems to be working. I was now able to set up a local site.
