### ISSUE TITLE
Donation Form is not working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#7]
We have a donation form set up with PayPal, but it's not working. When I click on one of the options, nothing seems to happen. It's not taking me to PayPal as expected.

@jenlampton - Can you check this out and see what happened?

Did I break it? If so, sorry. 

https://events.backdropcms.org/donate

**Comment by jenlampton** [comment]
I can look at this in about 45 minutes. Can you explain what you mean by "not working"? I can retest then but this might save me 2 minutes :)

**Comment by stpaultim** [comment]
@jenlampton - you must have been responding via email and did not see the edits to the original ticket (i learned my lesson :-). 

Clicking on any of the links doesn't do anything.

**Comment by oadaeh** [comment]
This seems to me to be working now. I just made a donation via the credit card button.

**Comment by stpaultim** [comment]
@jenlampton - We just got this report in Zulip about the donation form not working.

```
I've registered for the event successfully, but I cannot proceed with 
the donation ...I select the debit/credit card method → fill in cc 
details, address → tick the "I confirm that I am of legal age" 
checkbox → click "Pay now" → nothing happens - no error message or anything
```

I was able to make a PayPal donation yesterday, using the PayPal button.

**Comment by stpaultim** [comment]
NOTE: I tested a credit card payment using the credit card button with the same results. When you click "Pay Now" nothing happens. No error, no sign of any action. 

This form seems to be hard-coded into node--10.tpl.php

I think we'll need @jenlampton or @quicksketch to help with this.

**Comment by stpaultim** [comment]
The PayPal and Pay Later buttons seem to work. But the Debit or Credit Card button doesn't. 

![paypal](https://user-images.githubusercontent.com/3144571/135915459-ff3a767a-698b-484f-9923-c9d65843ef1c.png)

**Comment by quicksketch** [comment]
Debit or Credit card button works for me, but I do have to enter "A friendly message?" first, which is silly. If we can't make it optional we should populate it with some default text and hide it from display.

**Comment by stpaultim** [comment]
@quicksketch - Thanks! Never thought to try that. 

We could also put some help text indicating that the field is required. But, it is silly to require a "friendly message."

**Comment by jenlampton** [comment]
I thought to try that. It doesn't work :(

**Comment by stpaultim** [comment]
This must be fixed, because we're not getting any more reports. I'll close issue.
