### ISSUE TITLE
Put the schedule on the site

### ISSUE THREAD

**Issue by oadaeh** [backdrop-ops/events.backdropcms.org#9]
Create infrastructure (content types, views, etc.) for having the schedule on the site, including being able to create a personal schedule based on some flagging mechanism.

This might be better as a meta issue.

**Comment by irinaz** [comment]
Schedule is set via view https://events.backdropcms.org/schedule 

#29 can be used to address personal schedule.

**Comment by irinaz** [comment]
#29 can be used to address personal schedule.
